### ISSUE TITLE
Feedback To-do's

### ISSUE THREAD

**Issue by sharonvopzeeland** [MelvinIdema/blok-tech-team#53]
- [x] Remove heart in nav (Sharon
- [x] Workout flow (All)
- [x] Change bevestig -> naar afspraken (Dana)
- [x] Pupple api -> nieuwe pupple inladen (Melvin & Bram) -> aparte issue
- [x] Register pages (Martin) -> aparte issue

**Comment by sharonvopzeeland** [comment]
Linkjes in footer zijn nu ook gelinkt aan pagina's, alleen de calender moet nog gelinkd worden

**Comment by sharonvopzeeland** [comment]
> Linkjes in footer zijn nu ook gelinkt aan pagina's, alleen de calender moet nog gelinkd worden

nvm gefixd
